# Generated by Django 4.2.7 on 2023-12-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercis_is_checked_delete_usersexercises'),
        ('users', '0002_account_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exerxises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exercises.exercis'),
            preserve_default=False,
        ),
    ]
