# Generated by Django 4.2.7 on 2023-12-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_exerxises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='exerxises',
            new_name='exerсises',
        ),
    ]
