# Generated by Django 4.2.7 on 2023-12-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_exerxises_account_exerсises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='exerсises',
        ),
    ]
