# Generated by Django 4.2.7 on 2023-12-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercis_is_checked_delete_usersexercises'),
        ('users', '0005_remove_account_exerсises'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exerсises',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exercises.exercis'),
        ),
    ]
