# Generated by Django 4.2.7 on 2023-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercis_is_checked_delete_usersexercises'),
        ('users', '0006_account_exerсises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='exerсises',
        ),
        migrations.AddField(
            model_name='account',
            name='exerсises',
            field=models.ManyToManyField(to='exercises.exercis'),
        ),
    ]
