# Generated by Django 4.2.7 on 2023-12-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_account_exerсises_account_exerсises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='exerсises',
        ),
    ]
