# Generated by Django 4.2.7 on 2023-11-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.programs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.users')),
            ],
        ),
        migrations.CreateModel(
            name='users_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercises')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.users')),
            ],
        ),
        migrations.CreateModel(
            name='programs_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercises')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.programs')),
            ],
        ),
    ]
