# Generated by Django 4.2.7 on 2023-12-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='users_exercises',
            name='exercis_id',
        ),
        migrations.RemoveField(
            model_name='users_exercises',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users_programs',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='users_programs',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='exercises',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='exercises',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='image',
            field=models.ImageField(blank=True, upload_to='exercises/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterIndexTogether(
            name='exercises',
            index_together={('id', 'slug')},
        ),
        migrations.DeleteModel(
            name='programs_exercises',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='users_exercises',
        ),
        migrations.DeleteModel(
            name='users_programs',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='type',
        ),
        migrations.AddField(
            model_name='exercises',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exercises.category'),
            preserve_default=False,
        ),
    ]
