# Generated by Django 4.2.7 on 2023-12-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_category_remove_users_exercises_exercis_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exercises',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='exercises',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='exercises',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='users_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.programs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.users')),
            ],
        ),
        migrations.CreateModel(
            name='users_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercises')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.users')),
            ],
        ),
        migrations.CreateModel(
            name='programs_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercises')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.programs')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
