# Generated by Django 4.2.7 on 2023-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_users_alter_exercises_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('group', models.CharField(max_length=20)),
                ('img', models.ImageField(default='no_image.jpg', upload_to='product_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='users_exercises',
            name='exercis_id',
        ),
        migrations.RemoveField(
            model_name='users_exercises',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users_programs',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='users_programs',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='users_exercises',
        ),
        migrations.DeleteModel(
            name='users_programs',
        ),
    ]
