# Generated by Django 4.2.7 on 2023-12-03 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_exercis_remove_users_exercises_exercis_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField()),
                ('exercis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercis')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
