# Generated by Django 4.2.7 on 2023-12-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_usersexercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercis',
            name='is_checked',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UsersExercises',
        ),
    ]
