# Generated by Django 4.2.7 on 2023-12-03 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0006_exercis_is_checked_delete_usersexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercis_id', models.ManyToManyField(to='exercises.exercis')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
