# Generated by Django 4.2.7 on 2023-12-08 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0008_remove_exercis_is_checked_usersexercises_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersexercises',
            name='exercis_id',
        ),
        migrations.RemoveField(
            model_name='usersexercises',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usersexercises',
            name='exercis_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exercises.exercis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersexercises',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
